var R = require("../rlab");
var v = [1,3,5];
print("v.max()=", v.max());
print("v.min()=", v.min());
print("v.sum()=", v.sum());
print("v.normalize()=", v.normalize());
print("v.normalize().sum()=", v.normalize().sum());
print("v.product()=", v.product());
print("v.mean()=", v.mean());
print("v.range()=", v.range());
print("v.median()=", v.median());
print("v.variance()=", v.variance());
print("v.sd()=", v.sd(), " sd^2=", v.sd()*v.sd());
print("v.cov(v)=", v.cov(v), "v.cor(v)=", v.cor(v));
print("factorial(5)=", R.factorial(5));
print('hist(rnorm(10000,5,2))=', R.rnorm(10000, 5, 2).hist(1,3,7).str(0));