var R = require("../lib/statistics");
var v = [1,3,5];
print("v=%s", v);
print("v.samples(10)=%s", v.samples(10));
print("v.max()=%s", v.max());
print("v.min()=%s", v.min());
print("v.sum()=%s", v.sum());
print("v.normalize()=%s", v.normalize());
print("v.normalize().sum()=%s", v.normalize().sum());
print("v.product()=%s", v.product());
print("v.mean()=%s", v.mean());
print("v.range()=%s", v.range());
print("v.median()=%s", v.median());
print("v.variance()=%s", v.variance());
print("v.sd()=%s sd^2=%s", v.sd(), v.sd()*v.sd());
print("v.cov(v)=%s v.cor(v)=", v.cov(v), v.cor(v));
print("factorial(5)=%s", R.factorial(5));
print('rnorm(10,5,2)=%s', R.rnorm(10, 5, 2).str());
print('hist(rnorm(100,5,2))=%j', R.rnorm(100, 5, 2).hist(3,7,1));